---
title: "Your Python Journey Map: Guide to Chapters and Resources"
---

# Just Enough Python

This series introduces the essential components of the programming language Python. The focus is on the programming language and not on the craft of programming. The content does not discuss everything about Python but provides a foundation so you can take it further. The material has been prepared for students in the Faculty of Business and Law at Curtin University but has been updated to include modern AI-assisted programming techniques.

## Core Python Fundamentals

1. [Python in the Age of AI](01_python_in_the_age_of_ai.qmd)
2. [Basic Python Syntax](02_basic_python_syntax.qmd)
3. [Values](03_values.qmd)
4. [Variables](04_variables.qmd)
5. [Output](05_output.qmd)
6. [Input](06_input.qmd)
7. [Operators](07_operators.qmd)

## Functions and Control Flow

8. [Using Functions](08_using_functions.qmd)
9. [Creating Functions](09_creating_functions.qmd)
10. [Making Decisions](10_making_decisions.qmd)

## Data Structures and Iteration

11. [Lists](11_lists.qmd)
12. [Going Loopy](12_going_loopy.qmd)
13. [Strings](13_strings.qmd)
14. [Dictionaries](14_dictionaries.qmd)

## Working with Data and Files

15. [Files](15_files.qmd)

## Code Quality and Organization

16. [Errors and Exceptions](16_errors_and_exceptions.qmd)
17. [Debugging](17_debugging.qmd)
18. [Testing](18_testing.qmd)
19. [Modules and Packages](19_modules_and_packages.qmd)
20. [Orientating your Objects](20_orientating_your_objects.qmd)

## Practical Python Usage

21. [How to Run Python Code](21_how_to_run_python_code.qmd)
22. [How to Install Python](22_how_to_install_python_testing.qmd)
23. [Getting Help](23_getting_help.qmd)

## Python in the AI Era

24. [AI Programming Assistants](24_ai_programming_assistants.qmd)
25. [Python for AI Integration](25_python_ai_integration.qmd)
26. [AI Assistance Tips](26_ai_assistance_tips.qmd)
27. [Intentional Prompting for Python Developers](27_intentional_prompting.qmd)

## Project: Build Your Own AI Chatbot

- [Building Your AI-Enhanced Python Chatbot](chatbot_project.qmd)

## Similar Python Tutorials

Here are some free beginner tutorials that inspired this series. They have a data science focus but you may find them useful in your learning journey.

* [Introduction to Python (Microsoft)](https://docs.microsoft.com/en-us/learn/modules/intro-to-python/)
* [Python (Kaggle)](https://www.kaggle.com/learn/python)
* [Whirlwind Tour of Python](https://github.com/jakevdp/WhirlwindTourOfPython/blob/master/Index.ipynb)
* [Learn Python in 1 hour (Video)](https://youtu.be/kqtD5dpn9C8)
* [Learn Python Basics for Data Analysis](https://openclassrooms.com/en/courses/2304731-learn-python-basics-for-data-analysis)